[package]
name = "lift"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.15"
enum-iterator = "1.4.1"
rand = "0.8.5"
image = "0.24.6"
sdl2 = "0.34.5"
glow = "0.12.0"
fontdue = "0.7.3"
serde_json = "1.0.95"
serde = { version = "1.0.159", features = ["derive"] }


